In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [4]:
df=pd.read_csv('dataset/gurgaon_properties.csv')

In [5]:
df.tail()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3956,3 BHK Flat in Sector 103 Gurgaon,flat,indiabulls centrum park,1.90,5681.0,3344.0,Carpet area: 3344 (310.67 sq.m.),3,4,3+,"pooja room,study room,servant room,others","Sector 103 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...",Located in the popular residential address of ...,"['4 Wardrobe', '1 Water Purifier', '10 Fan', '...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
3957,3 BHK Flat in Sector 36 Sohna,flat,signature global park 4,0.72,6660.0,1081.0,Super Built up area 1081(100.43 sq.m.),3,2,3,not available,"Sector 36 Sohna, Gurgaon, Haryana",3.0,NaN,Under Construction,NaN,Residential apartment for sell.Located in sect...,[],NaN,NaN
3958,2 Bedroom House for sale in Shivpuri,house,independent,2.00,11111.0,1800.0,Plot area 200(167.23 sq.m.),2,2,1,not available,"Gurgaon Sector -7, Shivpuri, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Arya...",Interested to sell independent house/villa.Pla...,"['2 Fan', 'No AC', 'No Bed', 'No Chimney', 'No...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
3959,2 BHK Flat in Sector 90 Gurgaon,flat,shree vardhman flora,0.75,5769.0,1300.0,Carpet area: 1300 (120.77 sq.m.),2,2,3,not available,"Sector 90, Sector 90 Gurgaon, Gurgaon, Haryana",8.0,North-East,undefined,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",Best in class property available at sector 90 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Amenities5 out of 5'..."
3960,4 Bedroom House for sale in Laxman Vihar Phase 2,house,independent,0.92,15257.0,603.0,Plot area 67(56.02 sq.m.),4,4,3,others,"2676, Laxman Vihar Phase 2, Gurgaon, Haryana",4.0,East,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...",Because all connectivity are available all tra...,"['2 Fan', '10 Light', '3 Wardrobe', 'No AC', '...",NaN,NaN

In [6]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3732,4 Bedroom House for sale in Sector 67A Gurgaon,house,4s aradhya homes,1.83,6778.0,2700.0,Plot area 300(250.84 sq.m.),4,4,2,pooja room,"K101, Sector 67A Gurgaon, Gurgaon, Haryana",4.0,East,0 to 1 Year Old,"['Airia Mall', 'Sohna Road', 'Southern Periphe...","Well connected, in the heart of gurgaon, near ...","['3 Wardrobe', '6 Fan', '1 Stove', '1 Microwav...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3030,9 Bedroom House for sale in C Block Sushant Lo...,house,independent,14.00,39886.0,3510.0,Plot area 390(326.09 sq.m.),9,9,3+,servant room,"C Block Sushant Lok Phase 1, Gurgaon, Haryana",4.0,North,5 to 10 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Corner building,north facing,good location,",NaN,['Water Storage'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1091,5 Bedroom House for sale in Jyoti Park,house,independent,1.16,11717.0,990.0,Carpet area: 110 (91.97 sq.m.),5,4,2,not available,"Jyoti Park, Sector 7, Jyoti Park, Gurgaon, Har...",1.0,North-East,undefined,NaN,"Square plot, airy atmosphere, property ventila...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3097,3 BHK Flat in Sector 78 Gurgaon,flat,umang monsoon breeze,0.95,5491.0,1730.0,Built Up area: 1730 (160.72 sq.m.),3,3,2,not available,"Sector 78 Gurgaon, Gurgaon, Haryana",9.0,East,1 to 5 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...",Good construction and well maintained society....,"['3 Fan', '1 Exhaust Fan', '2 Geyser', '7 Ligh...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
699,3 BHK Flat in Sector 65 Gurgaon,flat,m3m golfestate,7.00,18181.0,3850.0,Carpet area: 3850 (357.68 sq.m.),3,3,2,store room,"Sector 65 Gurgaon, Gurgaon, Haryana",12.0,North,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",3 bedroom 3850 sq.Ft. Middle floor apartment a...,"['3 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction5 out of..."